name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.2
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Compose
      run: docker-compose -f docker-compose.yml build

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🚀 Build Notification: ${{ github.event_name }} sur ${{ github.ref }}"
        to: alexandre.aloesode@laplateforme.io
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Bonjour,
          
          La pipeline a été exécutée avec succès sur le repo **${{ github.repository }}**.
          - 🏷️ Ref: ${{ github.ref }}
          - 📦 Event: ${{ github.event_name }}
          - 🕒 Date: ${{ github.event.head_commit.timestamp }}

          Vérifie les logs ici: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          Cordialement,
          Votre pipeline GitHub Actions.
